Document: irssi-python
Title: Debian irssi-python Manual
Author: <insert document author here>
Abstract: This manual describes what irssi-python is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/irssi-python/irssi-python.sgml.gz

Format: postscript
Files: /usr/share/doc/irssi-python/irssi-python.ps.gz

Format: text
Files: /usr/share/doc/irssi-python/irssi-python.text.gz

Format: HTML
Index: /usr/share/doc/irssi-python/html/index.html
Files: /usr/share/doc/irssi-python/html/*.html
